### ISSUE TITLE
Feature Request: Add `value` and `_` as aliases to `expect`

### ISSUE THREAD

**Issue by danielpclark** [ysbaddaden/minitest.cr#13]
First of all great job with this shard.  It works brilliantly!

**Feature Request**
Ruby's Minitest has the original method defined on the underscore method and aliases `value` and `expect` to it.

Original:
```ruby
##
# Returns a value monad that has all of Expectations methods
# available to it.
#
# Also aliased to #value and #expect for your aesthetic pleasure:
#
#         _(1 + 1).must_equal 2
#     value(1 + 1).must_equal 2
#    expect(1 + 1).must_equal 2
#
# This method of expectation-based testing is preferable to
# straight-expectation methods (on Object) because it stores its
# test context, bypassing our hacky use of thread-local variables.
#
# At some point, the methods on Object will be deprecated and then
# removed.

def _ value = nil, &block
  Minitest::Expectation.new block || value, self
end

alias value _
alias expect _
```
src: [seattlerb/minitest/lib/minitest/spec.rb](https://github.com/seattlerb/minitest/blob/f95ef007ec64d956d88fedc37fd2ed7e106b777e/lib/minitest/spec.rb#L287-L309)

**Comment by ysbaddaden** [comment]
I thought about adding these aliases, then retracted.

A first issue is that `_` already has a meaning in Crystal: it's the blackhole operator. For example if I don't care about a block parameter, so I put `_` and the variable won't exist. Using it for something entirely diferent would only bring confusion.

Another issue is that a Crystal convention is to avoid aliases, so there is always only one way to call something. This greatly reduces the number of things to learn and remember. Since `expect` is more common than `value`, only the former is available.

**Comment by danielpclark** [comment]
I see.  Rust is the same way with `_`.  I've written a lot of Ruby tests with `_(thing).must_equal` syntax so I thought I'd ask about it.  Good to know.
